apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: inf
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana

